### ISSUE TITLE
RubyMotion macOS App Icon in template seems to be missing transparency / alpha channel

### ISSUE THREAD

**Issue by bolandross** [amirrajan/rubymotion-applied#112]
I noticed that the macOS template for RubyMotion projects uses an app icon with no transparency, so it looks quite bad in the macOS dock.

![macos dock](https://user-images.githubusercontent.com/5481702/47567764-b6e5bd80-d92f-11e8-8383-c758ea525f45.png)

In the RubyMotion installer and iOS variant, the icons seem to be fine.

**Comment by Red-Menace** [comment]
I finally got around to starting up my [RubyMotionBits repository](https://github.com/Red-Menace/RubyMotionBits) (trying not to embarrass myself too much, I don't do this stuff for a living).  It has a few macOS icon asset catalog resources you can use, including that base RM icon that I fixed with an alpha channel.

**Comment by digitalmoksha** [comment]
@Red-Menace very cool!  Thank you for sharing!

**Comment by ediathome** [comment]
Just added a pull request to the templates repository with a transparent version...

**Comment by bolandross** [comment]
Are there any news regarding this?

**Comment by Red-Menace** [comment]
The pull request mentioned earlier adding a transparency was committed.  You can use **motion repo** to update your local templates (or download/clone the template repository).

**Comment by bolandross** [comment]
That's great news, thank you!
