### ISSUE TITLE
`no resource identifier found`

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-applied#78]
No worky: https://github.com/gregmolnar/Hello

**Comment by hboon** [comment]
Instead of manually downloading the jar and vendoring, you can use https://github.com/HipByte/motion-gradle instead.

In your `Gemfile`:

    gem 'motion-gradle'

`Rakefile`:

    app.gradle do
        repository 'https://maven.google.com'
        dependency 'com.android.support:design:25.4.0' #I didn't double check the version
    end

Then:

    bundle install
    rake gradle:install

Should work for a vanilla RubyMotion Android project. Probably have to adapt it for `motion-flow`.

cc @gregmolnar

**Comment by gregmolnar** [comment]
@hboon I tried that but the issue is, Flow already includes a different version of `appcompat` and it causes issues. I guess the best would be to figure out how to make Flow not include the libraries included by the main project as it's mentioned here:
 https://github.com/HipByte/Flow/blob/master/lib/motion-flow/loader.rb#L29 
I will look into how to make that work.

**Comment by gregmolnar** [comment]
I think made this work. @amirrajan would you be open to use `motion-gradle` rather then `vendor_project` in `Flow` to manage dependencies? In my sample app if I do so, it nicely allows me to override them and use a newer version of them if necessary. If you are OK with it, I will open a PR on `Flow` and `motion-gradle` to make them work together.

**Comment by amirrajan** [comment]
related: https://github.com/amirrajan/rubymotion-applied/issues/79
